# Generated by Django 5.2.4 on 2025-08-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='platillos/'),
        ),
    ]
