# Generated by Django 5.2.4 on 2025-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_platillo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platillo',
            name='ingredientes',
            field=models.TextField(help_text='Lista separada por comas'),
        ),
    ]
