# Generated by Django 5.2.4 on 2025-08-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
