# Generated by Django 5.2.4 on 2025-08-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cuenta_platillos_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mesa'),
        ),
    ]
