# Generated by Django 5.2.4 on 2025-08-16 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cuenta_mesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='cerrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ventas_totales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_totales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dinero_en_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corte de Caja',
                'verbose_name_plural': 'Cortes de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Extra',
                'verbose_name_plural': 'Gastos Extras',
                'ordering': ['-fecha'],
            },
        ),
    ]
